CREATE SEQUENCE SEQ_CLIENTE   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRABAJO   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICIO  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ARCHIVO   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TS        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TA        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAQUINA   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COLA      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACTURA   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAGO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ==== TABLAS ====

CREATE TABLE CLIENTE (
    CLIENTE_ID     NUMBER(10)    NOT NULL,
    TIPO_DOC       VARCHAR2(5)   NOT NULL,
    NUM_DOC        VARCHAR2(20)  NOT NULL,
    NOMBRE         VARCHAR2(150) NOT NULL,
    TELEFONO       VARCHAR2(20),
    EMAIL          VARCHAR2(120),
    ESTADO         VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
    CREADO_EN      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CLIENTE    PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT UQ_CLI_DOC    UNIQUE (NUM_DOC),
    CONSTRAINT CK_CLI_TDOC   CHECK (TIPO_DOC IN ('CC','NIT','CE','PAS')),
    CONSTRAINT CK_CLI_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE TRABAJO (
    TRABAJO_ID     NUMBER(10)    NOT NULL,
    CLIENTE_ID     NUMBER(10)    NOT NULL,
    NOMBRE         VARCHAR2(200) NOT NULL,
    DESCRIPCION    CLOB,
    ESTADO         VARCHAR2(15)  DEFAULT 'PENDIENTE' NOT NULL,
    FECHA_INICIO   TIMESTAMP,
    FECHA_FIN      TIMESTAMP,
    CREADO_EN      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TRABAJO    PRIMARY KEY (TRABAJO_ID),
    CONSTRAINT FK_TRB_CLI    FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT CK_TRB_ESTADO CHECK (ESTADO IN ('PENDIENTE','EN_PROCESO','COMPLETADO','CANCELADO'))
);

CREATE TABLE SERVICIO (
    SERVICIO_ID    NUMBER(10)    NOT NULL,
    NOMBRE         VARCHAR2(100) NOT NULL,
    DESCRIPCION    VARCHAR2(300),
    PRECIO_BASE    NUMBER(10,2)  NOT NULL,
    ESTADO         VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_SERVICIO    PRIMARY KEY (SERVICIO_ID),
    CONSTRAINT UQ_SRV_NOMBRE  UNIQUE (NOMBRE),
    CONSTRAINT CK_SRV_PRECIO  CHECK (PRECIO_BASE >= 0),
    CONSTRAINT CK_SRV_ESTADO  CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE ARCHIVO (
    ARCHIVO_ID     NUMBER(10)    NOT NULL,
    NOMBRE         VARCHAR2(200) NOT NULL,
    EXTENSION      VARCHAR2(10),
    RUTA           VARCHAR2(500),
    TAMANIO_KB     NUMBER(10),
    ESTADO         VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
    CREADO_EN      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ARCHIVO    PRIMARY KEY (ARCHIVO_ID),
    CONSTRAINT CK_ARH_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE TRABAJO_SERVICIO (
    TS_ID          NUMBER(10)    NOT NULL,
    TRABAJO_ID     NUMBER(10)    NOT NULL,
    SERVICIO_ID    NUMBER(10)    NOT NULL,
    CANTIDAD       NUMBER(5)     DEFAULT 1 NOT NULL,
    PRECIO_UNIT    NUMBER(10,2)  NOT NULL,
    SUBTOTAL       NUMBER(10,2)  GENERATED ALWAYS AS (CANTIDAD * PRECIO_UNIT) VIRTUAL,
    CONSTRAINT PK_TS         PRIMARY KEY (TS_ID),
    CONSTRAINT FK_TS_TRB     FOREIGN KEY (TRABAJO_ID)  REFERENCES TRABAJO(TRABAJO_ID)  ON DELETE CASCADE,
    CONSTRAINT FK_TS_SRV     FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO(SERVICIO_ID),
    CONSTRAINT CK_TS_CANT    CHECK (CANTIDAD >= 1),
    CONSTRAINT CK_TS_PRECIO  CHECK (PRECIO_UNIT >= 0)
);

CREATE TABLE TRABAJO_ARCHIVO (
    TA_ID          NUMBER(10)    NOT NULL,
    TRABAJO_ID     NUMBER(10)    NOT NULL,
    ARCHIVO_ID     NUMBER(10)    NOT NULL,
    COPIAS         NUMBER(5)     DEFAULT 1 NOT NULL,
    INSTRUCCIONES  CLOB,
    CONSTRAINT PK_TA         PRIMARY KEY (TA_ID),
    CONSTRAINT FK_TA_TRB     FOREIGN KEY (TRABAJO_ID) REFERENCES TRABAJO(TRABAJO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TA_ARH     FOREIGN KEY (ARCHIVO_ID) REFERENCES ARCHIVO(ARCHIVO_ID),
    CONSTRAINT CK_TA_COPIAS  CHECK (COPIAS >= 1)
);

CREATE TABLE MAQUINA (
    MAQUINA_ID     NUMBER(10)    NOT NULL,
    NOMBRE         VARCHAR2(100) NOT NULL,
    DESCRIPCION    VARCHAR2(300),
    TIPO           VARCHAR2(50),
    ESTADO         VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
    CREADO_EN      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MAQUINA    PRIMARY KEY (MAQUINA_ID),
    CONSTRAINT CK_MAQ_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE COLAMAQUINA (
    COLA_ID          NUMBER(10)    NOT NULL,
    MAQUINA_ID       NUMBER(10)    NOT NULL,
    TRABAJO_ID       NUMBER(10)    NOT NULL,
    PRIORIDAD        NUMBER(2)     DEFAULT 5 NOT NULL,
    ESTADO           VARCHAR2(15)  DEFAULT 'PENDIENTE' NOT NULL,
    INICIO_ESTIMADO  TIMESTAMP,
    FIN_ESTIMADO     TIMESTAMP,
    INICIO_REAL      TIMESTAMP,
    FIN_REAL         TIMESTAMP,
    CREADO_EN        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_COLA        PRIMARY KEY (COLA_ID),
    CONSTRAINT FK_COLA_MAQ    FOREIGN KEY (MAQUINA_ID) REFERENCES MAQUINA(MAQUINA_ID),
    CONSTRAINT FK_COLA_TRB    FOREIGN KEY (TRABAJO_ID) REFERENCES TRABAJO(TRABAJO_ID),
    CONSTRAINT CK_COLA_ESTADO CHECK (ESTADO IN ('PENDIENTE','EN_PROCESO','COMPLETADO','CANCELADO')),
    CONSTRAINT CK_COLA_PRIO   CHECK (PRIORIDAD BETWEEN 1 AND 10)
);

CREATE TABLE FACTURA (
    FACTURA_ID     NUMBER(10)    NOT NULL,
    TRABAJO_ID     NUMBER(10)    NOT NULL,
    FECHA          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    SUBTOTAL       NUMBER(10,2)  NOT NULL,
    IMPUESTO       NUMBER(10,2)  DEFAULT 0 NOT NULL,
    TOTAL          NUMBER(10,2)  NOT NULL,
    ESTADO         VARCHAR2(10)  DEFAULT 'PENDIENTE' NOT NULL,
    CREADO_EN      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FACTURA    PRIMARY KEY (FACTURA_ID),
    CONSTRAINT UQ_FAC_TRB    UNIQUE (TRABAJO_ID),
    CONSTRAINT FK_FAC_TRB    FOREIGN KEY (TRABAJO_ID) REFERENCES TRABAJO(TRABAJO_ID),
    CONSTRAINT CK_FAC_ESTADO CHECK (ESTADO IN ('PENDIENTE','PAGADO','ANULADO'))
);

CREATE TABLE PAGO (
    PAGO_ID        NUMBER(10)    NOT NULL,
    FACTURA_ID     NUMBER(10)    NOT NULL,
    METODO         VARCHAR2(30)  NOT NULL,
    MONTO          NUMBER(10,2)  NOT NULL,
    FECHA          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    REFERENCIA_EXT VARCHAR2(100),
    ESTADO         VARCHAR2(12)  DEFAULT 'COMPLETADO' NOT NULL,
    CREADO_EN      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PAGO       PRIMARY KEY (PAGO_ID),
    CONSTRAINT FK_PAG_FAC    FOREIGN KEY (FACTURA_ID) REFERENCES FACTURA(FACTURA_ID),
    CONSTRAINT CK_PAG_METODO CHECK (METODO IN ('EFECTIVO','TARJETA','TRANSFERENCIA','NEQUI','DAVIPLATA')),
    CONSTRAINT CK_PAG_MONTO  CHECK (MONTO > 0),
    CONSTRAINT CK_PAG_ESTADO CHECK (ESTADO IN ('COMPLETADO','ANULADO','PENDIENTE'))
);

COMMIT;


-- Trigger para cada tabla (patrón uniforme):

CREATE OR REPLACE TRIGGER TRG_CLIENTE_AI
BEFORE INSERT ON CLIENTE FOR EACH ROW
BEGIN
    IF :NEW.CLIENTE_ID IS NULL THEN
        :NEW.CLIENTE_ID := SEQ_CLIENTE.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TRABAJO_AI
BEFORE INSERT ON TRABAJO FOR EACH ROW
BEGIN
    IF :NEW.TRABAJO_ID IS NULL THEN
        :NEW.TRABAJO_ID := SEQ_TRABAJO.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SERVICIO_AI
BEFORE INSERT ON SERVICIO FOR EACH ROW
BEGIN
    IF :NEW.SERVICIO_ID IS NULL THEN
        :NEW.SERVICIO_ID := SEQ_SERVICIO.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ARCHIVO_AI
BEFORE INSERT ON ARCHIVO FOR EACH ROW
BEGIN
    IF :NEW.ARCHIVO_ID IS NULL THEN
        :NEW.ARCHIVO_ID := SEQ_ARCHIVO.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TS_AI
BEFORE INSERT ON TRABAJO_SERVICIO FOR EACH ROW
BEGIN
    IF :NEW.TS_ID IS NULL THEN :NEW.TS_ID := SEQ_TS.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TA_AI
BEFORE INSERT ON TRABAJO_ARCHIVO FOR EACH ROW
BEGIN
    IF :NEW.TA_ID IS NULL THEN :NEW.TA_ID := SEQ_TA.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MAQUINA_AI
BEFORE INSERT ON MAQUINA FOR EACH ROW
BEGIN
    IF :NEW.MAQUINA_ID IS NULL THEN
        :NEW.MAQUINA_ID := SEQ_MAQUINA.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_COLA_AI
BEFORE INSERT ON COLAMAQUINA FOR EACH ROW
BEGIN
    IF :NEW.COLA_ID IS NULL THEN :NEW.COLA_ID := SEQ_COLA.NEXTVAL; END IF;
END;
/

-- Trigger anti-solapamiento en Oracle:
CREATE OR REPLACE TRIGGER TRG_COLA_NO_SOLAPAMIENTO
BEFORE INSERT OR UPDATE ON COLAMAQUINA FOR EACH ROW
DECLARE
    v_cnt NUMBER;
BEGIN
    IF :NEW.ESTADO = 'EN_PROCESO' THEN
        SELECT COUNT(*) INTO v_cnt
        FROM COLAMAQUINA
        WHERE MAQUINA_ID = :NEW.MAQUINA_ID
          AND ESTADO     = 'EN_PROCESO'
          AND COLA_ID   <> NVL(:NEW.COLA_ID, -1);
        IF v_cnt > 0 THEN
            RAISE_APPLICATION_ERROR(-20001,
                'La máquina ' || :NEW.MAQUINA_ID || ' ya tiene un trabajo EN_PROCESO');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_FACTURA_AI
BEFORE INSERT ON FACTURA FOR EACH ROW
BEGIN
    IF :NEW.FACTURA_ID IS NULL THEN
        :NEW.FACTURA_ID := SEQ_FACTURA.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAGO_AI
BEFORE INSERT ON PAGO FOR EACH ROW
BEGIN
    IF :NEW.PAGO_ID IS NULL THEN
        :NEW.PAGO_ID := SEQ_PAGO.NEXTVAL;
    END IF;
END;
/

COMMIT;